# NumPy
- Numeric Python
- Alternative to Python List: NumPy Array
- Calculations over entire arrays
- Easy and Fast

In [1]:
import numpy as np

In [2]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

In [3]:
np_height = np.array(height)
np_height

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [4]:
np_weight = np.array(weight)
np_weight

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [5]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

## Remarks
- NumPy arrays: contain only one type
- Typical arithmetic operators, such as `+, -, * and /` have a different meaning for regular Python lists and numpy arrays.

## NumPy Subsetting

In [6]:
bmi[1]

20.97505668934241

In [7]:
bmi > 23

array([False, False, False,  True, False])

In [8]:
bmi[bmi > 23]

array([24.7473475])

## 2D NumPy Arrays

In [9]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [10]:
np_2d.shape

(2, 5)

In [11]:
np_2d[0][2]

1.71

In [12]:
np_2d[0, 2]

1.71

In [13]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [14]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

## Basic Statistics

In [15]:
height = np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))

In [16]:
np.mean(np_city[:, 0])

1.750282

In [17]:
np.median(np_city[:, 0])

1.75

In [18]:
np.corrcoef(np_city[:, 0], np_city[:, 1])

array([[1.00000000e+00, 9.86596194e-04],
       [9.86596194e-04, 1.00000000e+00]])

In [19]:
np.std(np_city[:, 0])

0.20029453431384492